# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
    {
        :name => "pg96-primary",
        :ipaddr => "192.168.3.101",
        :mem => "1024"
    },
    {
        :name => "pg96-replica1",
        :ipaddr => "192.168.3.102",
        :mem => "1024"
    },
    {
        :name => "pg96-replica2",
        :ipaddr => "192.168.3.103",
        :mem => "1024"
    }
]

Vagrant.configure("2") do |config|
    servers.each do |server|
        config.vm.define server[:name] do |srv|

            srv.vm.box = "bento/ubuntu-18.04"
            srv.vm.network :private_network, ip: server[:ipaddr]
            srv.vm.hostname = server[:name]

            srv.vm.provider :virtualbox do |vb|
                vb.name = server[:name]
                vb.memory = server[:mem]
                vb.gui = false
            end

            srv.vm.provision "shell", inline: <<-SHELL
                locale-gen en_US && update-locale
                cat > /etc/apt/sources.list <<EOF
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic main restricted
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates main restricted

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic universe
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates universe

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic multiverse
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates multiverse

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security main restricted
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security universe
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security multiverse
EOF
                apt-get -y update
                apt-get -y install curl ca-certificates daemontools

                #
                # PostgreSQL 9.6 Setup
                #
                curl -s #{ENV['APT_MIRROR']}/mirror/apt.postgresql.org/ACCC4CF8.asc | apt-key add -
                echo "deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" > /etc/apt/sources.list.d/pgdg.list
                apt-get -y update
                apt-get -y install postgresql-9.6 postgresql-9.6-partman
                if [ $(hostname) = 'pg96-primary' ]
                then
                    systemctl stop postgresql@9.6-main
                    pg_dropcluster 9.6 main
                    pg_createcluster --lc-collate=en_US --lc-ctype=en_US --lc-messages=C --lc-monetary=C --lc-numeric=C --lc-time=C 9.6 main
                    systemctl start postgresql@9.6-main
                    #su -l postgres -c "psql -f /vagrant/template_change.sql"
                    su -l postgres -c "psql <<EOF
alter user postgres password 'postgres@123!';

update pg_database set datistemplate = FALSE where datname = 'template1';
drop database template1;
create database template1 with template = template0 encoding = 'UTF8' lc_ctype='en_US.utf8' lc_collate='en_US.utf8';
update pg_database set datistemplate = TRUE where datname = 'template1';
create database test lc_ctype='en_US' lc_collate='en_US' encoding='LATIN1' template='template0';
update pg_database set encoding = pg_char_to_encoding('UTF8') where datname = 'test';
EOF"
                    su -l postgres -c "psql -l"
                    su -l postgres -c "psql -d test -c \\"create extension pg_partman\\""
                    su -l postgres -c "psql -d test <<EOF
CREATE TABLE users (
  id    SERIAL PRIMARY KEY,
  email VARCHAR(40) NOT NULL UNIQUE,
  created_at    TIMESTAMP NOT NULL
);

INSERT INTO users (email, created_at)
SELECT
  'user_' || seq || '@' || (
    CASE (RANDOM() * 2)::INT
      WHEN 0 THEN 'gmail'
      WHEN 1 THEN 'hotmail'
      WHEN 2 THEN 'yahoo'
    END
  ) || '.com' AS email,
  timestamp '2016-01-10 20:00:00' +
       random() * (timestamp '2020-01-20 20:00:00' -
                   timestamp '2016-01-10 20:00:00')
FROM GENERATE_SERIES(1, 500000) seq;

CREATE INDEX users_created_at_idx ON users(created_at);

VACUUM ANALYZE users;
EOF"
                fi

                #
                # SSH Key Authentication
                #
                su -l postgres -c "mkdir ~/.ssh; chmod 700 ~/.ssh"
                su -l postgres -c "cp /vagrant/keys/test_rsa ~/.ssh/id_rsa; chmod 600 ~/.ssh/id_rsa"
                su -l postgres -c "cp /vagrant/keys/test_rsa.pub ~/.ssh/id_rsa.pub; chmod 600 ~/.ssh/id_rsa.pub"
                su -l postgres -c "cp /vagrant/keys/test_rsa.pub ~/.ssh/authorized_keys; chmod 600 ~/.ssh/authorized_keys"
                
                #
                # WAL-G Setup
                #
                wget -nv https://github.com/wal-g/wal-g/releases/download/v0.2.15/wal-g.linux-amd64.tar.gz
                tar -xzf wal-g.linux-amd64.tar.gz
                mv wal-g /usr/local/bin
                rm wal-g.linux-amd64.tar.gz

                mkdir -p /etc/wal-g/environment
                chmod 0755 /etc/wal-g
                chmod 0755 /etc/wal-g/environment
                
                #
                # WAL-G Scripts
                #
                ENVDIR=/etc/wal-g/environment
                echo "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin" > $ENVDIR/PATH
                echo "/var/run/postgresql" > $ENVDIR/PGHOST
                echo "/var/lib/postgresql/9.6/main" > $ENVDIR/PGDATA
                echo "5432" > $ENVDIR/PGPORT
                echo "postgres" > $ENVDIR/PGUSER
                echo "#{ENV['AWS_ACCOUNT_ID']}" > $ENVDIR/AWS_ACCOUNT_ID
                echo "#{ENV['AWS_ACCESS_KEY_ID']}" > $ENVDIR/AWS_ACCESS_KEY_ID
                echo "#{ENV['AWS_SECRET_ACCESS_KEY']}" > $ENVDIR/AWS_SECRET_ACCESS_KEY
                echo "#{ENV['AWS_DEFAULT_REGION']}" > $ENVDIR/AWS_DEFAULT_REGION
                #echo "#{ENV['WALG_STAGING_GPG_KEY_ID']}" > $ENVDIR/WALE_GPG_KEY_ID
                echo "#{ENV['WALG_S3_PREFIX']}/replica_upgrade_testing/9.6" > $ENVDIR/WALG_S3_PREFIX
                chown -R postgres:postgres $ENVDIR

                # Configure PostgreSQL WAL archiving
                echo "wal_level = replica" >> /etc/postgresql/9.6/main/conf.d/wal-g.conf
                echo "archive_mode = on" >> /etc/postgresql/9.6/main/conf.d/wal-g.conf
                echo "archive_command = 'envdir /etc/wal-g/environment /usr/local/bin/wal-g wal-push %p'" >> /etc/postgresql/9.6/main/conf.d/wal-g.conf
                echo "max_wal_senders = 5" >> /etc/postgresql/9.6/main/conf.d/replication.conf
                echo "listen_addresses = '*'" >> /etc/postgresql/9.6/main/conf.d/replication.conf
                echo "hot_standby = on" >> /etc/postgresql/9.6/main/conf.d/replication.conf
                echo "max_replication_slots = 10" >> /etc/postgresql/9.6/main/conf.d/replication.conf
                echo "host         replication            replicator      192.168.3.0/24      md5" >> /etc/postgresql/9.6/main/pg_hba.conf
                chown postgres:postgres /etc/postgresql/9.6/main/conf.d/*.conf

                su -l postgres -c "echo 'export PATH=/usr/lib/postgresql/9.6/bin:\$PATH' >> /var/lib/postgresql/.pgsql_profile"
                su -l postgres -c "echo '*:*:*:replicator:replicator123' >> /var/lib/postgresql/.pgpass"
                su -l postgres -c "echo '*:*:*:postgres:postgres@123!' >> /var/lib/postgresql/.pgpass"
                su -l postgres -c "chmod 0600 /var/lib/postgresql/.pgpass"

                if [ $(hostname) = 'pg96-primary' ]
                then
                    systemctl enable postgresql@9.6-main
                    systemctl restart postgresql@9.6-main

                    su -l postgres -c "psql -c \\"create user replicator replication password 'replicator123'\\""
                    su -l postgres -c "psql -c \\"select * from pg_create_physical_replication_slot('replica1')\\""
                    su -l postgres -c "psql -c \\"select * from pg_create_physical_replication_slot('replica2')\\""

                    su -l postgres -c "envdir /etc/wal-g/environment /usr/local/bin/wal-g backup-push /var/lib/postgresql/9.6/main"
                else
                    systemctl stop postgresql@9.6-main
                    rm -rf /var/lib/postgresql/9.6/main
                    su -l postgres -c "envdir /etc/wal-g/environment /usr/local/bin/wal-g backup-fetch /var/lib/postgresql/9.6/main LATEST"
                    echo "standby_mode = on" >> /var/lib/postgresql/9.6/main/recovery.conf
                    echo "primary_conninfo = 'host=192.168.3.101 user=replicator'" >> /var/lib/postgresql/9.6/main/recovery.conf
                    echo "restore_command = 'envdir /etc/wal-g/environment /usr/local/bin/wal-g wal-fetch %f %p'" >> /var/lib/postgresql/9.6/main/recovery.conf
                    if [ $(hostname) = 'pg96-replica1' ]
                    then
                        echo "primary_slot_name = 'replica1'" >> /var/lib/postgresql/9.6/main/recovery.conf
                    elif [ $(hostname) = 'pg96-replica2' ]
                    then
                        echo "primary_slot_name = 'replica2'" >> /var/lib/postgresql/9.6/main/recovery.conf
                    fi
                    chown postgres:postgres /var/lib/postgresql/9.6/main/recovery.conf

                    systemctl enable postgresql@9.6-main
                    systemctl start postgresql@9.6-main
                    su -l postgres -c "psql -c \\"select pg_is_in_recovery()\\""
                fi


                #
                # Install PG 12
                #
                apt-get -y install postgresql-12 postgresql-12-partman
                if [ $(hostname) = 'pg96-primary' ]
                then
                    systemctl stop postgresql@12-main
                    ###pg_dropcluster 12 main
                    ###pg_createcluster --lc-collate=en_US --lc-ctype=en_US --lc-messages=C --lc-monetary=C --lc-numeric=C --lc-time=C 12 main
                    ###systemctl start postgresql@12-main
                    ###su -l postgres -c "psql -p 5433 <<EOF
###update pg_database set datistemplate = FALSE where datname = 'template1';
###drop database template1;
###create database template1 with template = template0 encoding = 'UTF8' lc_ctype='en_US.UTF-8' lc_collate='en_US.UTF-8';
###update pg_database set datistemplate = TRUE where datname = 'template1';
###EOF"
                    ###systemctl stop postgresql@12-main
                else
                    systemctl stop postgresql@12-main
                    rm -rf /var/lib/postgresql/12/main
                fi

                echo "wal_level = replica" >> /etc/postgresql/12/main/conf.d/wal-g.conf
                echo "archive_mode = on" >> /etc/postgresql/12/main/conf.d/wal-g.conf
                echo "archive_command = 'envdir /etc/wal-g/environment /usr/local/bin/wal-g wal-push %p'" >> /etc/postgresql/12/main/conf.d/wal-g.conf
                echo "max_wal_senders = 5" >> /etc/postgresql/12/main/conf.d/replication.conf
                echo "max_replication_slots = 10" >> /etc/postgresql/12/main/conf.d/replication.conf
                echo "listen_addresses = '*'" >> /etc/postgresql/12/main/conf.d/replication.conf
                echo "hot_standby = on" >> /etc/postgresql/12/main/conf.d/replication.conf
                echo "restore_command = 'envdir /etc/wal-g/environment /usr/local/bin/wal-g wal-fetch %f %p'" >> /etc/postgresql/12/main/conf.d/replication.conf
                if [ $(hostname) = 'pg96-primary' ]
                then
                    # Just pick a random replica to use as possible new primary
                    echo "primary_conninfo = 'host=192.168.3.102 user=replicator'" >> /etc/postgresql/12/main/conf.d/replication.conf
                else
                    echo "primary_conninfo = 'host=192.168.3.101 user=replicator'" >> /etc/postgresql/12/main/conf.d/replication.conf
                    if [ $(hostname) = 'pg96-replica1' ]
                    then
                        echo "primary_slot_name = 'replica1'" >> /etc/postgresql/12/main/conf.d/replication.conf
                    elif [ $(hostname) = 'pg96-replica2' ]
                    then
                        echo "primary_slot_name = 'replica2'" >> /etc/postgresql/12/main/conf.d/replication.conf
                    fi
                fi
                chown postgres:postgres /etc/postgresql/12/main/conf.d/*.conf
                echo "host         replication            replicator      192.168.3.0/24      md5" >> /etc/postgresql/12/main/pg_hba.conf

                #systemctl stop postgresql@9.6-main
                #systemctl disable postgresql@9.6-main
                #su -l postgres -c "sh /vagrant/check_upgrade.sh && sh /vagrant/upgrade.sh"
            SHELL
        end
    end
end
