# -*- mode: ruby -*-
# vi: set ft=ruby :

# define hostname
NAME = "pg96"

Vagrant.configure("2") do |config|
    config.vm.define NAME
    config.vm.box = "dts/centos7"
    config.vm.hostname = NAME

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
        config.cache.enable :yum
    end

    config.vm.provision "shell", inline: <<-SHELL
        yum -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        yum -y install postgresql96-server postgresql96-contrib

        su -l postgres -c "echo 'export PATH=/usr/pgsql-9.6/bin:\$PATH' >> /var/lib/pgsql/.pgsql_profile"
        su -l postgres -c "/usr/pgsql-9.6/bin/initdb -D /var/lib/pgsql/9.6/data"
        sudo systemctl enable postgresql-9.6
        sudo systemctl start postgresql-9.6
    SHELL
end
