# -*- mode: ruby -*-
# vi: set ft=ruby :

# Load setup Vagrantfile
load "../Vagrantfile"

# define hostname
NAME = "ubuntu2204-pg14"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision "shell", inline: "DEBIAN_FRONTEND=noninteractive apt-get -y install postgresql-14 postgresql-14-partman"
end

