# -*- mode: ruby -*-
# # vi: set ft=ruby :

# Specify minimum Vagrant version and Vagrant API version
VAGRANTFILE_API_VERSION = "2"

servers = [
    {
        :name => "pg12-pg1",
        :ipaddr => "192.168.122.16",
        :mem => "1024"
    },
    {
        :name => "pg12-pg2",
        :ipaddr => "192.168.122.26",
        :mem => "1024"
    }
]

# Create servers
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.hostmanager.enabled = false
    config.vbguest.auto_update = false

    servers.each do |server|
        config.vm.define server[:name] do |srv|
            srv.vm.box = "dts/centos7"
            srv.vm.network :private_network, ip: server[:ipaddr]
            srv.vm.hostname = server[:name]

            srv.vm.provider :virtualbox do |vb|
                vb.name = server[:name]
                vb.memory = server[:mem]
                vb.gui = false
            end

            srv.vm.provision "shell", inline: <<-SHELL
              #echo "No Proxy"
              echo "Proxy Server Setup"
              echo "proxy=http://192.168.1.3:3128" >> /etc/yum.conf
              
              yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

              # Enable PGDG12 Repo while still in dev
              sed -i -e '/\[pgdg12\]/,/^\[/s/enabled=0/enabled=1/' /etc/yum.repos.d/pgdg-redhat-all.repo

              #yum update -y
              yum install -y postgresql12-server postgresql12-contrib

              su -l postgres -c "echo 'export PATH=/usr/pgsql-12/bin:\$PATH' >> /var/lib/pgsql/.pgsql_profile"
              su -l postgres -c "/usr/pgsql-12/bin/initdb -D /var/lib/pgsql/12/data"
            SHELL
        end
    end
end
