# -*- mode: ruby -*-
# vi: set ft=ruby :

# Load setup Vagrantfile
load "../Vagrantfile.setup"

redis_servers = [
    {
        :name => "redis01",
        :ipaddr => "192.168.61.101",
        :mem => "512"
    },
    {
        :name => "redis02",
        :ipaddr => "192.168.61.102",
        :mem => "512"
    },
    {
        :name => "redis03",
        :ipaddr => "192.168.61.103",
        :mem => "512"
    },
    {
        :name => "redis04",
        :ipaddr => "192.168.61.104",
        :mem => "512"
    },
    {
        :name => "redis05",
        :ipaddr => "192.168.61.105",
        :mem => "512"
    },
    {
        :name => "redis06",
        :ipaddr => "192.168.61.106",
        :mem => "512"
    }
]

# Build the ip_addr:port string for the Redis cluster creation command
redis_cluster_string = ""
redis_servers.each do |rs|
  redis_cluster_string += " " + rs[:ipaddr] + ":7000"
end

Vagrant.configure("2") do |config|
  redis_servers.each do |server|
    config.vm.define server[:name] do |redis|
      #redis.vm.box = "bento/ubuntu-20.04"
      redis.vm.hostname = server[:name]
      redis.vm.network :private_network, ip: server[:ipaddr]
      redis.vm.provider :virtualbox do |vb|
        vb.name = server[:name]
        vb.memory = server[:mem]
      end

      redis.vm.provision "shell", inline: <<-SHELL
export DEBIAN_FRONTEND=noninteractive
sudo add-apt-repository ppa:redislabs/redis
apt -y update
apt -y install redis-server

# Change these default configs
sed -i 's/^bind .*/bind 127.0.0.1 #{server[:ipaddr]}/' /etc/redis/redis.conf
sed -i 's/^port .*/port 7000/' /etc/redis/redis.conf
sed -i 's/protected-mode .*/protected-mode no/' /etc/redis/redis.conf
sed -i 's/appendonly .*/appendonly yes/' /etc/redis/redis.conf

# Add these configs
echo "cluster-enabled yes" >> /etc/redis/redis.conf
echo "cluster-config-file nodes.conf" >> /etc/redis/redis.conf
echo "cluster-node-timeout 15000" >> /etc/redis/redis.conf

systemctl restart redis-server

# If this is the last machine in the group, run the Redis cluster setup
if [[ "#{server[:name]}" = "#{redis_servers.last[:name]}" ]]; then
  echo "redis_cluster_string: #{redis_cluster_string}"
  echo "redis-cli --cluster create #{redis_cluster_string} --cluster-yes --cluster-replicas 1"
  redis-cli --cluster create #{redis_cluster_string} --cluster-yes --cluster-replicas 1
fi
SHELL
    end
  end

  #config.vm.define "postgres" do |postgres|
    #postgres.vm.hostname = "postgres"
    #postgres.vm.network :private_network, ip: "192.168.61.111"
    #postgres.vm.provision "shell", inline: "apt -y install postgresql-12"
  #end

end
