# -*- mode: ruby -*-
# vi: set ft=ruby :

# define hostname
NAME = "centos7-postgresql10"

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define NAME
  config.vm.box = "centos/7"


  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    rpm -Uvh https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
    yum update -y
    yum install -y postgresql10-server postgresql10-contrib

    su -l postgres -c "/usr/pgsql-10/bin/initdb -D /var/lib/pgsql/10/data"
    su -l postgres -c "/usr/pgsql-10/bin/pg_ctl -D /var/lib/pgsql/10/data start -w"
  SHELL

end
