# -*- mode: ruby -*-
# vi: set ft=ruby :

# define hostname
NAME = "pg10"

Vagrant.configure("2") do |config|
    config.vm.define NAME
    config.vm.box = "bento/centos-7"
    config.vm.hostname = NAME

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
        config.cache.enable :yum
    end

    config.vm.provision "shell", inline: <<-SHELL
        yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        yum install -y postgresql10-server postgresql10-contrib

        su -l postgres -c "echo 'export PATH=/usr/pgsql-10/bin:\$PATH' >> /var/lib/pgsql/.pgsql_profile"
        su -l postgres -c "/usr/pgsql-10/bin/initdb -D /var/lib/pgsql/10/data"
        
        sudo systemctl enable postgresql-10
        sudo systemctl start postgresql-10
    SHELL

end
