# -*- mode: ruby -*-
# vi: set ft=ruby :

# define hostname
NAME = "ubuntu1804-pg10"

Vagrant.configure("2") do |config|
    config.vm.define NAME
    config.vm.box = "bento/ubuntu-18.04"
    #config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = NAME

    config.vm.provision "shell", inline: <<-SHELL
        apt-get -y install curl ca-certificates
        curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
        echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
        apt-get -y update
        apt-get -y install postgresql-10
    SHELL
end
