# -*- mode: ruby -*-
# vi: set ft=ruby :

# Load setup Vagrantfile
load "../Vagrantfile.setup.Ubuntu-20.04"

# define hostname
NAME = "ubuntu2004"

Vagrant.configure("2") do |config|
    config.vm.define NAME
    config.vm.hostname = NAME
    config.vm.provision "shell", inline: "apt update"
end

