# -*- mode: ruby -*-
# # vi: set ft=ruby :

# Load setup Vagrantfile
#vagrant_git_dir = "/Users/donseiler/git/dtseiler/vagrants"
#ubuntu2204_vagrantfile = vagrant_git_dir + "/Vagrantfile.setup.Ubuntu-22.04"
#load ubuntu2204_vagrantfile if File.exists?(ubuntu2204_vagrantfile)
load "../Vagrantfile.setup.Ubuntu-22.04"

NAME = "ubuntu2204-base"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    #config.vm.define NAME
    #config.vm.hostname = NAME
    #config.vm.provision "shell", inline: "apt update"
end
