# -*- mode: ruby -*-
# vi: set ft=ruby :

# Load setup Vagrantfile
load "../../Vagrantfile.setup.Ubuntu-22.04"

# define hostname
NAME = "ubuntu2204-pg15"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision "shell", inline: "DEBIAN_FRONTEND=noninteractive apt-get -y install postgresql-15 postgresql-15-partman"
end

