# -*- mode: ruby -*-
# vi: set ft=ruby :

# define hostname
NAME = "pg-patch-test"

Vagrant.configure("2") do |config|
    config.vm.define NAME
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.hostname = NAME

    config.vm.provision "shell", inline: <<-SHELL
        export DEBIAN_FRONTEND=noninteractive
        cat > /etc/apt/sources.list <<EOF
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic main restricted
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates main restricted

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic universe
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates universe

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic multiverse
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates multiverse

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security main restricted
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security universe
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security multiverse
EOF
        apt -y update
        apt -y install curl ca-certificates gnupg
        curl -s #{ENV['APT_MIRROR']}/mirror/apt.postgresql.org/ACCC4CF8.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg >/dev/null
        echo "deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" > /etc/apt/sources.list.d/pgdg.list
        apt -y update

        curl -sO #{ENV['APT_MIRROR']}/mirror/apt.postgresql.org/pub/repos/apt/pool/main/p/postgresql-12/postgresql-12_12.5-1.pgdg18.04+1_amd64.deb
        curl -sO #{ENV['APT_MIRROR']}/mirror/apt.postgresql.org/pub/repos/apt/pool/main/p/pg-partman/postgresql-12-partman_4.4.1-1.pgdg18.04+1_amd64.deb
        apt -y install ./postgresql-12_12.5-1.pgdg18.04+1_amd64.deb
        apt -y install ./postgresql-12-partman_4.4.1-1.pgdg18.04+1_amd64.deb

        su -l postgres -c "psql -c \\"select version();\\""

        apt policy postgresql-12-partman

        mkdir -p /etc/systemd/system/postgresql.service.d/
        cat > /etc/systemd/system/postgresql.service.d/overrides.conf <<EOF
[Service]
ExecStartPre=/usr/bin/dpkg-query -s postgresql-12-partman
EOF
        echo "manual" | tee /etc/postgresql/12/main/start.conf
        systemctl daemon-reload
        systemctl stop postgresql

        apt -y --only-upgrade install postgresql-12 postgresql-12-partman

        echo "auto" | tee /etc/postgresql/12/main/start.conf
        systemctl daemon-reload
        systemctl start postgresql
        su -l postgres -c "psql -c \\"select version();\\""

        apt policy postgresql-12-partman

        journalctl -u postgresql
    SHELL
end
