# -*- mode: ruby -*-
# vi: set ft=ruby :

# Load setup Vagrantfile
load "../Vagrantfile.setup"

# define hostname
NAME = "ubuntu1804-pg12"

Vagrant.configure("2") do |config|
  config.vm.define NAME
  config.vm.hostname = NAME
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt -y install postgresql-common
    echo "initdb_options = '--data-checksums'" >> /etc/postgresql-common/createcluster.conf
    apt -y install postgresql-12
SHELL
end
