# -*- mode: ruby -*-
# vi: set ft=ruby :

# define hostname
NAME = "pg11"

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define NAME
  config.vm.box = "centos/7"


  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    rpm -Uvh https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm
    yum update -y
    yum install -y postgresql11-server postgresql11-contrib

    su -l postgres -c "echo 'export PATH=/usr/pgsql-11/bin:\$PATH' >> /var/lib/pgsql/.pgsql_profile"
    su -l postgres -c "/usr/pgsql-11/bin/initdb -D /var/lib/pgsql/11/data"
    sudo systemctl enable postgresql-11
    sudo systemctl start postgresql-11
    #su -l postgres -c "/usr/pgsql-11/bin/pg_ctl -D /var/lib/pgsql/11/data start -w"
  SHELL

end
