# -*- mode: ruby -*-
# vi: set ft=ruby :

# define hostname
NAME = "pg11"

Vagrant.configure("2") do |config|
    config.vm.define NAME
    config.vm.box = "bento/centos-7"
    config.vm.hostname = NAME

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
        config.cache.enable :yum
    end

    config.vm.provision "shell", inline: <<-SHELL
        yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        yum install -y postgresql11-server postgresql11-contrib

        su -l postgres -c "echo 'export PATH=/usr/pgsql-11/bin:\$PATH' >> /var/lib/pgsql/.pgsql_profile"
        su -l postgres -c "/usr/pgsql-11/bin/initdb -D /var/lib/pgsql/11/data"
        systemctl enable postgresql-11
        systemctl start postgresql-11
    SHELL

end
