# -*- mode: ruby -*-
# vi: set ft=ruby :

# define hostname
NAME = "pg94"

Vagrant.configure("2") do |config|
    config.vm.define NAME
    config.vm.box = "dts/centos7"
    config.vm.hostname = NAME

    if Vagrant.has_plugin?("vagrant-cachier")
        config.cache.scope = :box
        config.cache.enable :yum
    end

    config.vm.provision "shell", inline: <<-SHELL
        yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        #yum update -y
        yum install -y postgresql94-server postgresql94-contrib

        su -l postgres -c "echo 'export PATH=/usr/pgsql-9.4/bin:\$PATH' >> /var/lib/pgsql/.pgsql_profile"
        su -l postgres -c "/usr/pgsql-9.4/bin/initdb -D /var/lib/pgsql/9.4/data"
        sudo systemctl enable postgresql-9.4
        sudo systemctl start postgresql-9.4
    SHELL
end
