# -*- mode: ruby -*-
# vi: set ft=ruby :

# Load setup Vagrantfile
load "../Vagrantfile.setup"

# define hostname
NAME = "vault01"

Vagrant.configure("2") do |config|
    config.vm.define NAME
    config.vm.hostname = NAME
    config.vm.provision "shell", inline: <<-SHELL
export DEBIAN_FRONTEND=noninteractive
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
apt -y update
apt -y install vault
SHELL
end
