# -*- mode: ruby -*-
# # vi: set ft=ruby :

# Specify minimum Vagrant version and Vagrant API version
VAGRANTFILE_API_VERSION = "2"

servers = [
    {
        :name => "pg11-pub",
        :ipaddr => "192.168.3.16",
        :mem => "1024"
    },
    {
        :name => "pg11-sub",
        :ipaddr => "192.168.3.26",
        :mem => "1024"
    }
]

# Create servers
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.hostmanager.enabled = false
    config.vbguest.auto_update = false

    servers.each do |server|
        config.vm.define server[:name] do |srv|
            srv.vm.box = "dts/centos7"
            srv.vm.network :private_network, ip: server[:ipaddr]
            srv.vm.hostname = server[:name]

            srv.vm.provider :virtualbox do |vb|
                vb.name = server[:name]
                vb.memory = server[:mem]
                vb.gui = false
            end

            srv.vm.provision "shell", inline: <<-SHELL
              #echo "No Proxy"
              echo "Proxy Server Setup"
              echo "proxy=http://192.168.1.3:3128" >> /etc/yum.conf
              
              yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
              yum install -y postgresql11-server-11.2 postgresql11-contrib-11.2 pg_partman11

              su -l postgres -c "echo 'export PATH=/usr/pgsql-11/bin:\$PATH' >> /var/lib/pgsql/.pgsql_profile"
              su -l postgres -c "/usr/pgsql-11/bin/initdb -D /var/lib/pgsql/11/data"

              echo "listen_addresses = '*'" >> /var/lib/pgsql/11/data/postgresql.conf
              echo "wal_level = 'logical'" >> /var/lib/pgsql/11/data/postgresql.conf
              echo "host         dts            replicator      192.168.3.0/24      md5" >> /var/lib/pgsql/11/data/pg_hba.conf

              systemctl stop firewalld
              systemctl disable firewalld

              systemctl enable postgresql-11
              systemctl start postgresql-11
              su -l postgres -c "psql -a -f /vagrant/setup.sql"

              if [ $(hostname) = 'pg11-pub' ]
              then
                su -l postgres -c "psql -d dts -a -f /vagrant/pub.sql"
              else
                su -l postgres -c "psql -d dts -a -f /vagrant/sub.sql"
              fi
            SHELL
        end
    end
end
