# -*- mode: ruby -*-
# vi: set ft=ruby :

# define hostname
NAME = "pgbackrest-azure-test"

Vagrant.configure("2") do |config|
    config.vm.define NAME
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.hostname = NAME

    config.vm.provision "shell", inline: <<-SHELL
        cat > /etc/apt/sources.list <<EOF
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic main restricted
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates main restricted

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic universe
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates universe

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic multiverse
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates multiverse

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security main restricted
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security universe
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security multiverse
EOF
        apt-get -y update
        apt-get -y install curl ca-certificates
        curl -s #{ENV['APT_MIRROR']}/mirror/apt.postgresql.org/ACCC4CF8.asc | apt-key add -
        echo "deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" > /etc/apt/sources.list.d/pgdg.list
        apt-get -y update
        apt-get -y install postgresql-12

        echo "archive_mode = on" >> /etc/postgresql/12/main/postgresql.conf
        echo "archive_command = 'pgbackrest --stanza=main archive-push %p'" >> /etc/postgresql/12/main/postgresql.conf
        systemctl restart postgresql@12-main

        # Build pgbackrest dev-azure branch
        apt-get -y install rsync git devscripts build-essential valgrind lcov autoconf \
            autoconf-archive libssl-dev zlib1g-dev libxml2-dev libpq-dev pkg-config \
            libxml-checker-perl libyaml-libyaml-perl libdbd-pg-perl liblz4-dev liblz4-tool \
            zstd libzstd-dev bzip2 libbz2-dev unzip
        curl -sLO https://github.com/pgbackrest/pgbackrest/archive/dev-azure.zip
        unzip dev-azure.zip
        cd pgbackrest-dev-azure/src
        ./configure --prefix=/usr/local
        make && make install

        mkdir /etc/pgbackrest
        cat > /etc/pgbackrest/pgbackrest.conf <<EOF
[main]
pg1-path=/var/lib/postgresql/12/main

[global]
repo1-type=azure
repo1-path=/pgbackrest-test-$(date '+%Y%m%d%H%M%S')
repo1-azure-account=#{ENV['AZURE_STORAGE_ACCOUNT']}
repo1-azure-container=#{ENV['AZURE_STORAGE_CONTAINER']}
repo1-azure-key=#{ENV['AZURE_STORAGE_ACCESS_KEY']}
process-max=4
EOF
        chown -R postgres:postgres /etc/pgbackrest
        mkdir /var/log/pgbackrest
        chown -R postgres:postgres /var/log/pgbackrest

        su -l postgres -c "pgbackrest --stanza=main --log-level-console=info stanza-create"
        su -l postgres -c "pgbackrest --stanza=main --log-level-console=info backup"
    SHELL
end
