# -*- mode: ruby -*-
# vi: set ft=ruby :

# define hostname
NAME = "ubuntu1804-pg12"

Vagrant.configure("2") do |config|
    config.vm.define NAME
    config.vm.box = "bento/ubuntu-18.04"
    config.vm.hostname = NAME

    config.vm.provision "shell", inline: <<-SHELL
        cat > /etc/apt/sources.list <<EOF
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic main restricted
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates main restricted

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic universe
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates universe

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic multiverse
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-updates multiverse

deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security main restricted
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security universe
deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/archive.ubuntu.com/ubuntu/ bionic-security multiverse
EOF
        apt-get -y update
        apt-get -y install curl ca-certificates
        curl -s #{ENV['APT_MIRROR']}/mirror/apt.postgresql.org/ACCC4CF8.asc | apt-key add -
        echo "deb [arch=amd64] #{ENV['APT_MIRROR']}/mirror/apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" > /etc/apt/sources.list.d/pgdg.list
        apt-get -y update
        apt-get -y install postgresql-12 postgresql-12-partman
        echo "shared_preload_libraries = 'pg_partman_bgw'" >> /etc/postgresql/12/main/postgresql.conf
        systemctl restart postgresql
        su -l postgres -c "createdb test"
        su -l postgres -c "psql -d test -c \\"create schema partman\\""
        su -l postgres -c "psql -d test -c \\"create extension pg_partman schema partman\\""
        su -l postgres -c "psql -l"
        su -l postgres -c "psql -d test -c \\"\\dx\\""

        su -l postgres -c "psql -d test <<EOF
CREATE TABLE users (
  --id    INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  id    VARCHAR(36) PRIMARY KEY,
  email VARCHAR(40) NOT NULL UNIQUE,
  created_at    TIMESTAMP NOT NULL
);

-- Use a fake UUID generator here
INSERT INTO users (id, email, created_at)
SELECT
  md5(random()::text || clock_timestamp()::text)::uuid as id,
  'user_' || seq || '@' || (
    CASE (RANDOM() * 2)::INT
      WHEN 0 THEN 'gmail'
      WHEN 1 THEN 'hotmail'
      WHEN 2 THEN 'yahoo'
    END
  ) || '.com' AS email,
  timestamp '2016-01-10 20:00:00' +
       random() * (timestamp '2020-01-20 20:00:00' -
                   timestamp '2016-01-10 20:00:00')
FROM GENERATE_SERIES(1, 5000000) seq;

CREATE INDEX users_created_at_idx ON users(created_at);

SELECT date_trunc('month', created_at) as created_month, count(*)
FROM users
GROUP BY created_month
ORDER BY created_month;

VACUUM ANALYZE users;

CREATE TABLE users_part_template
  (LIKE users INCLUDING ALL);

ALTER TABLE users RENAME TO users_source; 

CREATE TABLE users
  (LIKE users_part_template INCLUDING DEFAULTS INCLUDING CONSTRAINTS)
PARTITION BY RANGE (created_at);

SELECT partman.create_parent('public.users', 'created_at', 'native', 'monthly', p_premake := 2, p_automatic_maintenance := 'off', p_template_table := 'public.users_part_template');
DROP TABLE users_default;
ALTER TABLE users_source RENAME TO users_default; 
ALTER TABLE users ATTACH PARTITION users_default DEFAULT;
UPDATE partman.part_config SET automatic_maintenance='on' WHERE parent_table='public.users';

\\timing on
CALL partman.partition_data_proc('public.users', '1 month');
VACUUM ANALYZE users;
VACUUM ANALYZE users_default;
REINDEX TABLE users_default;

SELECT date_trunc('month', created_at) as created_month, count(*)
FROM users
GROUP BY created_month
ORDER BY created_month;

SELECT nspname || '.' || relname AS "relation",
    pg_size_pretty(pg_relation_size(C.oid)) AS "size"
  FROM pg_class C
  LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
  WHERE nspname NOT IN ('pg_catalog', 'information_schema')
    AND relname like '%default%'
  ORDER BY pg_relation_size(C.oid) DESC;
EOF"
    SHELL
end
